sudo: required
# to solve the rake not find error
language: generic
# services required for the travis CI
services:
  - docker
# building the docker by using the Dockerfile.dev
before_install:
  - docker build -t harshitpareek/react-ci-dev -f Dockerfile.dev .
# running our test suit but adding coverage will make it exit with code 0 if everything goes well
script:
  - docker run harshitpareek/react-ci-dev npm run test -- --coverage