#specifiying language
language: node_js
sudo: required
# services required for the travis CI
services:
  - docker
# building the docker by using the Dockerfile.dev
before_install:
  - docker build -t harshitpareek/react-ci-dev -f Dockerfile.dev .
# running our test suit but adding coverage will make it exit with code 0 if everything goes well
script:
  - docker run -e CI=true harshitpareek/react-ci-dev npm run test